#!/usr/bin/env bash

cp -a ~/dev/helm/charts/stable/consul ~/dev/bossjones/boss-kubernetes-lab/charts/helm/consul
cp -a ~/dev/helm/charts/stable/dokuwiki ~/dev/bossjones/boss-kubernetes-lab/charts/helm/dokuwiki
cp -a ~/dev/helm/charts/stable/efs-provisioner ~/dev/bossjones/boss-kubernetes-lab/charts/helm/efs-provisioner
cp -a ~/dev/helm/charts/stable/elastic-stack ~/dev/bossjones/boss-kubernetes-lab/charts/helm/elastic-stack
cp -a ~/dev/helm/charts/stable/elasticsearch ~/dev/bossjones/boss-kubernetes-lab/charts/helm/elasticsearch
cp -a ~/dev/helm/charts/stable/elasticsearch-curator ~/dev/bossjones/boss-kubernetes-lab/charts/helm/elasticsearch-curator
cp -a ~/dev/helm/charts/stable/elasticsearch-exporter ~/dev/bossjones/boss-kubernetes-lab/charts/helm/elasticsearch-exporter
cp -a ~/dev/helm/charts/stable/eventrouter ~/dev/bossjones/boss-kubernetes-lab/charts/helm/eventrouter
cp -a ~/dev/helm/charts/stable/filebeat ~/dev/bossjones/boss-kubernetes-lab/charts/helm/filebeat
cp -a ~/dev/helm/charts/stable/fluent-bit ~/dev/bossjones/boss-kubernetes-lab/charts/helm/fluent-bit
cp -a ~/dev/helm/charts/stable/fluentd ~/dev/bossjones/boss-kubernetes-lab/charts/helm/fluentd
cp -a ~/dev/helm/charts/stable/fluentd-elasticsearch ~/dev/bossjones/boss-kubernetes-lab/charts/helm/fluentd-elasticsearch
cp -a ~/dev/helm/charts/stable/ghost ~/dev/bossjones/boss-kubernetes-lab/charts/helm/ghost
cp -a ~/dev/helm/charts/stable/gitlab-ce ~/dev/bossjones/boss-kubernetes-lab/charts/helm/gitlab-ce
cp -a ~/dev/helm/charts/stable/grafana ~/dev/bossjones/boss-kubernetes-lab/charts/helm/grafana
cp -a ~/dev/helm/charts/stable/graphite ~/dev/bossjones/boss-kubernetes-lab/charts/helm/graphite
cp -a ~/dev/helm/charts/stable/heapster ~/dev/bossjones/boss-kubernetes-lab/charts/helm/heapster
cp -a ~/dev/helm/charts/stable/heartbeat ~/dev/bossjones/boss-kubernetes-lab/charts/helm/heartbeat
cp -a ~/dev/helm/charts/stable/influxdb ~/dev/bossjones/boss-kubernetes-lab/charts/helm/influxdb
cp -a ~/dev/helm/charts/stable/jenkins ~/dev/bossjones/boss-kubernetes-lab/charts/helm/jenkins
cp -a ~/dev/helm/charts/stable/kibana ~/dev/bossjones/boss-kubernetes-lab/charts/helm/kibana
cp -a ~/dev/helm/charts/stable/locust ~/dev/bossjones/boss-kubernetes-lab/charts/helm/locust
cp -a ~/dev/helm/charts/stable/logstash ~/dev/bossjones/boss-kubernetes-lab/charts/helm/logstash
cp -a ~/dev/helm/charts/stable/metrics-server ~/dev/bossjones/boss-kubernetes-lab/charts/helm/metrics-server
cp -a ~/dev/helm/charts/stable/minio ~/dev/bossjones/boss-kubernetes-lab/charts/helm/minio
cp -a ~/dev/helm/charts/stable/mission-control ~/dev/bossjones/boss-kubernetes-lab/charts/helm/mission-control
cp -a ~/dev/helm/charts/stable/mongodb ~/dev/bossjones/boss-kubernetes-lab/charts/helm/mongodb
cp -a ~/dev/helm/charts/stable/mysql ~/dev/bossjones/boss-kubernetes-lab/charts/helm/mysql
cp -a ~/dev/helm/charts/stable/mysqldump ~/dev/bossjones/boss-kubernetes-lab/charts/helm/mysqldump
cp -a ~/dev/helm/charts/stable/nfs-client-provisioner ~/dev/bossjones/boss-kubernetes-lab/charts/helm/nfs-client-provisioner
cp -a ~/dev/helm/charts/stable/nfs-server-provisioner ~/dev/bossjones/boss-kubernetes-lab/charts/helm/nfs-server-provisioner
cp -a ~/dev/helm/charts/stable/nginx-ingress ~/dev/bossjones/boss-kubernetes-lab/charts/helm/nginx-ingress
cp -a ~/dev/helm/charts/stable/node-problem-detector ~/dev/bossjones/boss-kubernetes-lab/charts/helm/node-problem-detector
cp -a ~/dev/helm/charts/stable/node-red ~/dev/bossjones/boss-kubernetes-lab/charts/helm/node-red
cp -a ~/dev/helm/charts/stable/openvpn ~/dev/bossjones/boss-kubernetes-lab/charts/helm/openvpn
cp -a ~/dev/helm/charts/stable/owncloud ~/dev/bossjones/boss-kubernetes-lab/charts/helm/owncloud
cp -a ~/dev/helm/charts/stable/prometheus ~/dev/bossjones/boss-kubernetes-lab/charts/helm/prometheus
cp -a ~/dev/helm/charts/stable/prometheus-adapter ~/dev/bossjones/boss-kubernetes-lab/charts/helm/prometheus-adapter
cp -a ~/dev/helm/charts/stable/prometheus-blackbox-exporter ~/dev/bossjones/boss-kubernetes-lab/charts/helm/prometheus-blackbox-exporter
cp -a ~/dev/helm/charts/stable/prometheus-cloudwatch-exporter ~/dev/bossjones/boss-kubernetes-lab/charts/helm/prometheus-cloudwatch-exporter
cp -a ~/dev/helm/charts/stable/prometheus-couchdb-exporter ~/dev/bossjones/boss-kubernetes-lab/charts/helm/prometheus-couchdb-exporter
cp -a ~/dev/helm/charts/stable/prometheus-mysql-exporter ~/dev/bossjones/boss-kubernetes-lab/charts/helm/prometheus-mysql-exporter
cp -a ~/dev/helm/charts/stable/prometheus-node-exporter ~/dev/bossjones/boss-kubernetes-lab/charts/helm/prometheus-node-exporter
cp -a ~/dev/helm/charts/stable/prometheus-operator ~/dev/bossjones/boss-kubernetes-lab/charts/helm/prometheus-operator
cp -a ~/dev/helm/charts/stable/prometheus-postgres-exporter ~/dev/bossjones/boss-kubernetes-lab/charts/helm/prometheus-postgres-exporter
cp -a ~/dev/helm/charts/stable/prometheus-pushgateway ~/dev/bossjones/boss-kubernetes-lab/charts/helm/prometheus-pushgateway
cp -a ~/dev/helm/charts/stable/prometheus-rabbitmq-exporter ~/dev/bossjones/boss-kubernetes-lab/charts/helm/prometheus-rabbitmq-exporter
cp -a ~/dev/helm/charts/stable/prometheus-redis-exporter ~/dev/bossjones/boss-kubernetes-lab/charts/helm/prometheus-redis-exporter
cp -a ~/dev/helm/charts/stable/prometheus-to-sd ~/dev/bossjones/boss-kubernetes-lab/charts/helm/prometheus-to-sd
cp -a ~/dev/helm/charts/stable/rabbitmq ~/dev/bossjones/boss-kubernetes-lab/charts/helm/rabbitmq
cp -a ~/dev/helm/charts/stable/rabbitmq-ha ~/dev/bossjones/boss-kubernetes-lab/charts/helm/rabbitmq-ha
cp -a ~/dev/helm/charts/stable/redis ~/dev/bossjones/boss-kubernetes-lab/charts/helm/redis
cp -a ~/dev/helm/charts/stable/redis-ha ~/dev/bossjones/boss-kubernetes-lab/charts/helm/redis-ha
cp -a ~/dev/helm/charts/stable/sensu ~/dev/bossjones/boss-kubernetes-lab/charts/helm/sensu
cp -a ~/dev/helm/charts/stable/telegraf ~/dev/bossjones/boss-kubernetes-lab/charts/helm/telegraf
