apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your@email.com
    privateKeySecretRef:
      name: letsencrypt-prod # this can be changed by env, i.e letsencrypt-stage
    dns01:
      providers:
      - name: route53
        route53:
          region: us-east-1
